### ISSUE TITLE
Some Excitatory neuron subtypes are missing in cell type taxonomy?

### ISSUE THREAD

**Issue by DingWB** [AllenInstitute/scrattch.taxonomy#28]
Hi Nelson @UCDNJJ ,

Thanks for releasing this wonderful cell type taxonomy, I quickly performed an integration between our human single-cell DNA methylation dataset with your human sc-RNA-seq dataset. The integration of most Non-Neuron and Inhibitory neurons looks good, but not the excitatory neurons (Please see the following figures, mC stands for DNA methylation and RNA for your human single-cell RNA-seq data from HMBA):

![image](https://github.com/user-attachments/assets/67e2b6a8-10ce-49d1-9939-946b6027ecd4)

![image](https://github.com/user-attachments/assets/94d2337e-7f93-4781-839c-4eedc77d5fa7)

Could you please add more excitatory neuron subtypes to this cell type taxonomy? such as upper layer and deep layer IT, ET, NP and CT neurons.

**Comment by UCDNJJ** [comment]
Hi @DingWB,

Really nice work, the alignment of core basal ganglia types looks very good across modalities! Interesting how distinct the 29 MSN strip/mat hybrid is in methylation data. There are very few excitatory types in Basal Ganglia and you seem to have captured them. 

This taxonomy is restricted to Basal Ganglia so mapping cortical excitatory types will have to be done using another study such as Siletti et al. 2023. 

-Nelson

**Comment by DingWB** [comment]
Hi Nelson @UCDNJJ ,

I see. The snmC-seq methylation data I used here includes all brain regions from Wei Tian 2023 paper, in addition to Basal Ganglia, there are also cortex regions. 
I will use your cell type taxonomy first, and will add some excitatory neuron subtypes to this taxonomy if I identify some subtype that is not included in your taxonomy.

Thank you.

**Comment by DingWB** [comment]
Hi @UCDNJJ ,
I redo the integration with the basal ganglia regions only (['A25', 'ACC', 'A46', 'BNST', 'MD-Re', 'Pu', 'A24', 'CBL', 'CaB', 'IC', 'M1C', 'SI', 'NAC', 'MD', 'CBV', 'PN', 'V1C', 'GPe']). 
Indeed, we captured many excitatory neuron subtypes which are missing in your cell taxonomy.

I would like to add some excitatory neuron subtypes to your taxonomy, do you have any idea about how to do that?

![image](https://github.com/user-attachments/assets/27f7ad67-30fa-436a-b72a-83ed227764c9)

![image](https://github.com/user-attachments/assets/1fe7f28f-d31d-4841-ab46-77499b818a84)

**Comment by UCDNJJ** [comment]
From your list only these are basal ganglia: ['Pu', 'CaB', 'NAC', 'GPe'] but you could also include adjacent structures 'IC', 'SI'. 

Many of the regions you list are cortical which explains why you are picking up the layer specific excitatory types.

**Comment by DingWB** [comment]
Based on the sample sheet provided by the community, V1C, MTC, M1C, BNST are also basal ganglia regions

<img width="936" alt="image" src="https://github.com/user-attachments/assets/060238fe-e067-4051-a928-1871ed9fa7c9">

**Comment by UCDNJJ** [comment]
You can use the human reference brain atlas to understand what are basal ganglia regions: https://atlas.brain-map.org/atlas?atlas=265297126#atlas=265297126&plate=112363198&structure=10332&x=27897.8828125&y=61758.140625&zoom=-5&resolution=62.24&z=3. 

For example, V1C, M1C, MTC are all cortex.
